#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit 1
fi

appname=$1

cd $HOME/prog/$appname/

BACKUP_FOLDER=`date +"%Y-%m-%d %H-%M-%S"`

mkdir -p $HOME/Dropbox/prog/$appname
mkdir -p "$HOME/Dropbox/prog/$appname/backup/$BACKUP_FOLDER/"
mv $HOME/Dropbox/prog/$appname/envs.zip "$HOME/Dropbox/prog/$appname/backup/$BACKUP_FOLDER/envs.zip"
zip -r $HOME/Dropbox/prog/$appname/envs.zip  .env .envs/ secrets/ creds/
